version: '3.6'  
services:  
  flask-api:
    build:
      context: ./predictor
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
  slack-api:
    build:
      context: ./slack-integration
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "4390:4390"      
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:  
  redis_data: